-- エラーが出たらそこで止める（安全策）
\set ON_ERROR_STOP on

BEGIN;  -- まとめて作成するならトランザクションにしておくと便利

/* 1-A) 支出/収入を表す ENUM */
CREATE TYPE tx_kind AS ENUM ('expense', 'income');

/* 1-B) カテゴリテーブル（拡張しやすいように分離） */
CREATE TABLE categories (
  id   SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

/* 1-C) メインの取引テーブル */
CREATE TABLE transactions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL,
  tx_date      DATE NOT NULL,
  kind         tx_kind NOT NULL,
  amount       NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  name         TEXT,
  category_id  INT REFERENCES categories(id),
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

/* 1-D) よく検索する列にインデックス */
CREATE INDEX idx_tx_user_date ON transactions (user_id, tx_date);

COMMIT;  -- すべて成功していれば確定


INSERT INTO categories (name) VALUES
  ('食費'),
  ('光熱費');


-- 複数行テスト投入
INSERT INTO transactions (user_id, tx_date, kind, amount, name, category_id)
VALUES
  -- user_id = 1
  (1, CURRENT_DATE, 'expense',  500, 'コーヒー', 1),
  (1, CURRENT_DATE, 'expense',  850, 'ランチ',   1),
  (1, CURRENT_DATE, 'expense', 1200, '交通費',  2),

  -- user_id = 2
  (2, CURRENT_DATE, 'expense',  450, 'コーヒー', 1),
  (2, CURRENT_DATE, 'expense',  900, 'ランチ',   1),
  (2, CURRENT_DATE, 'expense', 1100, '交通費',  2);


-- 正しく入ったか確認
SELECT * FROM transactions LIMIT 5;
